spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:bboxx
    username: admin
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
# custom
bboxx:
  apple:
    issuer: aaaaa
    client-id: 11111111
  google:
    client-id: xxxxxxxxxxxx
  jwt:
    secret: basljdbfjhbdfjbeyfbev123sQEE0R44Zy345nlTYv8Gawxbc9vAHgUjlhruX2LSfxiLyeRqjn73J4
  firebase:
    project-id: "xx"
    client-id: "xxx"
    client-email: "xxxx"
    private-key: "xxxxxxx"
    private-key-id: "xxxxxxxxx"