### SignIn with kakao
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
  "providerType": "KAKAO",
  "authData": "FVK4XhrM50HGEDB5Ef5-hwqx84gXpVMxfF8__wo9dJcAAAF8eF3VqA"
}

### SignIn with Google
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
  "providerType": "GOOGLE",
  "authData": "google token"
}

### SignUp with kakao
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "providerType": "KAKAO",
  "authData": "nEMn5vSYWvWyeeno2mw64qdbuRRYHSi859h9pgopyNoAAAF8eM5xVg",
  "nickname": "닉네임이다아아!!"
}



### Validate jwt
POST http://localhost:8080/api/v1/auth/validate-jwt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6InBpa2FjaHUiLCJpZCI6IjEiLCJzdWIiOiIxIiwiaWF0IjoxNjMzMjcwNjE0LCJleHAiOjE2MzM4NzU0MTR9.oQ-t7YG0IlX8AiANdvzKFvf6pMWKo4i6zdQtBgE-QHs

{
  "jwt": "eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuLieuEpOyehOydtOuLpOyVhOyVhCEhIiwiaWQiOiIyIiwic3ViIjoiMiIsImlhdCI6MTYzNDk2NjI1OCwiZXhwIjoxNjM1NTcxMDU4fQ.R65brdMf5c7gvtilJTD7W7dqPnY4tTh-uHLdAvV9fNs"
}