### Generate nickname
POST http://localhost:8080/api/v1/generate-member-nickname
Content-Type: application/json

{
}

### Put Member info
PUT http://localhost:8080/api/v1/members/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuLieuEpOyehOydtOuLpOyVhOyVhCEhIiwiaWQiOiIxIiwic3ViIjoiMSIsImlhdCI6MTYzNDExMjkzMSwiZXhwIjoxNjM0NzE3NzMxfQ.Y0-cOEJ2fkjZst5cDpx169l-6xpF5N3Gi6OcsetSFNA

{
  "nickname": "닉네임변경이다아아아아아!!!!"
}


### Get Member Info
GET http://localhost:8080/api/v1/members/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuLieuEpOyehOydtOuLpOyVhOyVhCEhIiwiaWQiOiIxIiwic3ViIjoiMSIsImlhdCI6MTYzNDExMjM1MiwiZXhwIjoxNjM0NzE3MTUyfQ.2Qb9ikBEpMig3QvzWZNVnbaAh7b9T_vh7fV8sPsl2ds