### Post Register push token
POST http://localhost:8080/api/v1/push-tokens/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuLieuEpOyehOydtOuLpOyVhOyVhCEhIiwiaWQiOiIxIiwic3ViIjoiMSIsImlhdCI6MTYzODAwNTkyMSwiZXhwIjoxNjM5NDc3MTUwfQ.c-iUGSGHfFWm7KraD6BC4DCa1LU0CtXPuSSRSGyqRIg

{
  "ownerId": 1,
  "token": "this_is_to2ken_111112333333"
}

### Post Deregister push token
POST http://localhost:8080/api/v1/push-tokens/deregister
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuLieuEpOyehOydtOuLpOyVhOyVhCEhIiwiaWQiOiIxIiwic3ViIjoiMSIsImlhdCI6MTYzODAwNTkyMSwiZXhwIjoxNjM5NDc3MTUwfQ.c-iUGSGHfFWm7KraD6BC4DCa1LU0CtXPuSSRSGyqRIg

{
  "ownerId": 1
}

### Get push token
GET http://localhost:8080/api/v1/push-tokens/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuLieuEpOyehOydtOuLpOyVhOyVhCEhIiwiaWQiOiIxIiwic3ViIjoiMSIsImlhdCI6MTYzODAwNTkyMSwiZXhwIjoxNjM5NDc3MTUwfQ.c-iUGSGHfFWm7KraD6BC4DCa1LU0CtXPuSSRSGyqRIg

### Post Send notification
POST http://localhost:8080/api/v1/notifications/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuLieuEpOyehOydtOuLpOyVhOyVhCEhIiwiaWQiOiIxIiwic3ViIjoiMSIsImlhdCI6MTYzODAwNTkyMSwiZXhwIjoxNjM5NDc3MTUwfQ.c-iUGSGHfFWm7KraD6BC4DCa1LU0CtXPuSSRSGyqRIg

{
  "receiverId": 3,
  "emotionDiaryId": 3
}

### Get notification
GET http://localhost:8080/api/v1/notifications?receiver_id=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuLieuEpOyehOydtOuLpOyVhOyVhCEhIiwiaWQiOiIxIiwic3ViIjoiMSIsImlhdCI6MTYzODAwNTkyMSwiZXhwIjoxNjM5NDc3MTUwfQ.c-iUGSGHfFWm7KraD6BC4DCa1LU0CtXPuSSRSGyqRIg
