package bboxx.infrastructure.nicknamegenerator;

import bboxx.domain.member.commandmodel.NicknameGenerator;
import org.springframework.stereotype.Component;

import java.util.Random;

@Component
public class RandomNicknameGenerator implements NicknameGenerator {

    private static final String[] randomNickNameModifier = {
            "사랑스러운",
            "귀여운",
            "공손한",
            "모험심강한",
            "다정한",
            "야심찬",
            "쾌활한",
            "영악한",
            "배려하는",
            "용감한",
            "차분한",
            "유능한",
            "배려심넘치는",
            "자신감있는",
            "에너지넘치는",
            "용감한",
            "공손한",
            "궁금한",
            "결단력있는",
            "믿을수있는",
            "창의적인",
            "예술가",
            "낙천적인",
            "외향적인",
            "긍정적인",
            "마음이따뜻한",
            "지혜로운",
            "현실적인",
            "즐거운",
            "친절한",
            "공정한",
            "재미있는",
            "관대한",
            "정직한",
            "자애로운",
            "품위있는",
            "우아한",
            "카리스마있는",
            "재주있는",
            "친근한",
            "성숙한",
            "교양있는",
    };
    private static final String[] randomNickNameSubject = {
            "석류",
            "배",
            "레몬",
            "아로니아",
            "구아바",
            "코코넛",
            "유자",
            "수박",
            "블랙베리",
            "암바렐라",
            "레드향",
            "귤",
            "토마토",
            "체리",
            "복분자",
            "두리안",
            "올리브",
            "신고",
            "바나나",
            "살구",
            "라임",
            "망고스틴",
            "골드키위",
            "으름",
            "다래",
            "머루",
            "금귤",
            "청포도",
            "샤인머스켓",
            "용과",
            "스타프루트",
            "금감",
            "꽃사과",
            "청견",
            "캔털루프",
            "몽키 바나나",
            "핑거 라임",
            "참외",
            "자바애플",
            "두쿠",
            "구기자",
            "구즈베리",
            "두꾸",
            "스타애플",
            "페피노",
            "샤르도네",
            "머스크 멜론",
            "그린 망고",
            "홍옥",
            "가보스",
            "감",
            "포도",
            "사과",
            "파인애플",
            "복숭아",
            "칼라만시",
            "자몽",
            "멜론",
            "블루베리",
            "무화과",
            "한라봉",
            "천혜향",
            "딸기",
            "타마릴로",
            "아보카도",
            "설향멜론",
            "키위",
            "백도",
            "천도복숭아",
            "매실",
            "람부탄",
            "앵두",
            "델라웨어",
            "파파야",
            "모과",
            "살라크",
            "리슬링",
            "스위티",
            "마르멜로",
            "오렌지",
            "대추야자",
            "양광",
            "쿠푸아수",
            "건포도",
            "오디",
            "판타오",
            "플럼코트",
            "망고",
            "아사이베리",
            "시라",
            "포멜로",
            "만다린",
            "여주",
            "감귤",
            "패션프루트",
            "방울토마토",
            "영귤",
            "크랜베리",
            "산딸기",
            "거봉",
    };

    @Override
    public String generate() {
        return generateRandomModifier() +
                generateRandomSubject();
    }

    private String generateRandomModifier() {
        Random rand = new Random();
        return randomNickNameModifier[rand.nextInt(randomNickNameModifier.length)];
    }

    private String generateRandomSubject() {
        Random rand = new Random();
        return randomNickNameSubject[rand.nextInt(randomNickNameSubject.length)];
    }
}
